// globals.css

import './globals.css';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}){
  return (
    <>
      <html lang="en">
        <head>
          {/* Include your metadata and other head elements here */}
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
          {/* Other head elements */}
          <style>{inter.styles}</style>
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
